In [39]:
import numpy as np

In [9]:
a = [1, 2, 3, 4, 5, 6.6]

In [10]:
b = np.array(a, dtype=int)

In [11]:
b

array([1, 2, 3, 4, 5, 6])

In [12]:
b = np.array(a, dtype=str)

In [13]:
b

array(['1', '2', '3', '4', '5', '6.6'], dtype='<U3')

In [14]:
b.ndim

1

In [15]:
b.shape

(6,)

####2D array

In [19]:
b = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
            [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
            [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [20]:
b.shape

(3, 10)

In [21]:
b.size

30

In [22]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [24]:
b[1, 9]

19

In [25]:
b[0, 5]

5

In [26]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [27]:
b[0:2, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [31]:
b = np.array([1., 2., 3.,], dtype=np.float32)

In [32]:
b

array([1., 2., 3.], dtype=float32)

In [33]:
b = np.array([1., 2., 3.,], dtype=np.float64)

In [34]:
b

array([1., 2., 3.])

In [37]:
a = np.array([0, 1, 2, 3, 4])

In [38]:
b= np.array([5, 6, 7, 8, 9])

In [39]:
c = a + b

In [40]:
c

array([ 5,  7,  9, 11, 13])

In [41]:
a = np.array([5, 4, 8, 4, 3])
b = np.array([3, 5, 7, 1, 3])

In [42]:
d = np.subtract(a, b)

In [43]:
d

array([ 2, -1,  1,  3,  0])

In [44]:
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

In [45]:
c = a * 2

In [46]:
c

array([10,  8, 16,  8,  6])

In [47]:
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

#### Задание 1

In [4]:
a = np.array([[1, 2, 3, 3, 1],
            [6, 8, 11, 10, 7]])

In [5]:
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [11]:
mean_a = a.mean()

In [9]:
mean_a

5.2

#### Задание 2

In [14]:
a_centered = np.subtract(a, mean_a)

In [15]:
a_centered

array([[-4.2, -3.2, -2.2, -2.2, -4.2],
       [ 0.8,  2.8,  5.8,  4.8,  1.8]])

#### Задание 3

In [17]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]

In [19]:
a_centered_sp

15.68

In [20]:
a_centered_sp / a_centered.shape[0] - 1

6.84

#### Задание 4**

In [22]:
m = a.transpose()
m

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [23]:
np.cov(m)

array([[12.5, 15. , 20. , 17.5, 15. ],
       [15. , 18. , 24. , 21. , 18. ],
       [20. , 24. , 32. , 28. , 24. ],
       [17.5, 21. , 28. , 24.5, 21. ],
       [15. , 18. , 24. , 21. , 18. ]])

### “Работа с данными в Pandas”

#### Задание 1

In [1]:
import pandas as pd

In [4]:
author = pd.DataFrame({
    "author_id": [1, 2, 3],
    "author_name": ['Тургенев', 'Чехов', 'Островский']
})



In [7]:
book = pd.DataFrame({
    "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    "price": [450, 300, 350, 500, 450, 370, 290] 
})



#### Задание 2

In [18]:
author_price = pd.merge (author, book, on = 'author_id', how = 'inner')
author_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

#### Задание 3

In [30]:
top5 = author_price.nlargest(5, 'price')
top5


author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

#### Задание4

In [36]:
author_stat = author_price.groupby('author_name').agg({'price': ['min', 'max', 'mean']})
author_stat = author_stat.rename(columns={'min': 'min_price', 'max': 'max_price', 'mean': 'mean_price'})
author_stat


price                      
            min_price max_price  mean_price
author_name                                
Островский        290       370  330.000000
Тургенев          300       450  366.666667
Чехов             450       500  475.000000

#### Задание5

In [37]:
author_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
author_price

author_id author_name            book_title  price    cover
1          1    Тургенев                 Рудин    300  твердая
2          1    Тургенев     Дворянское гнездо    350   мягкая
0          1    Тургенев           Отцы и дети    450   мягкая
4          2       Чехов       Дама с собачкой    450  твердая
3          2       Чехов      Толстый и тонкий    500  твердая
6          3  Островский  Таланты и поклонники    290   мягкая
5          3  Островский                 Гроза    370   мягкая

In [40]:
book_info = pd.pivot_table(author_price, values='price', index='author_name', columns='cover', aggfunc=np.sum)
book_info['мягкая'] = book_info['мягкая'].fillna(0)
book_info['твердая'] = book_info['твердая'].fillna(0)
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      800.0    300.0
Чехов           0.0    950.0

In [41]:
book_info.to_pickle('book_info.pkl')

In [42]:
book_info2 = pd.read_pickle('book_info.pkl')

In [43]:
book_info.equals(book_info2)

True